name: Build LetsBeRational Windows Wheel - New Version

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Generate SWIG wrapper
        working-directory: ${{ github.workspace }}\cpp\third_party\jaekel
        run: generate_wrappers.bat

      - name: Build letsberational wheel
        working-directory: ${{ github.workspace }}\cpp\third_party\jaekel
        run: cibuildwheel --platform windows --output-dir wheelhouse

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: letsberational-wheel
          path: cpp/third_party/jaekel/wheelhouse/*.whl
