name: Build LetsBeRational Windows Wheel

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_wheel_windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build letsberational Windows wheel
        working-directory: ${{ github.workspace }}\cpp\third_party\jaeckel
        run: cibuildwheel --platform windows --output-dir wheelhouse

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-wheel
          path: ${{ github.workspace }}/cpp/third_party/jaeckel/wheelhouse/*.whl
